### ISSUE TITLE
正常安装后无法启动程序

### ISSUE THREAD

**Issue by wogong** [lord63/kindledxpush#10]
debian 8 x86_64 环境，使用 `sudo pip install kindledxpush` 安装成功。但是无法启动，具体错误如下：

    $ kindlepush -h
    Traceback (most recent call last):
      File "/usr/local/bin/kindlepush", line 9, in <module>
        load_entry_point('kindlepush==0.3.1', 'console_scripts', 'kindlepush')()
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
        return ep.load()
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
        ['__name__'])
      File "/usr/local/lib/python2.7/dist-packages/kindlepush/kindlepush.py", line 35, in <module>
        from kindlepush import __version__
    ImportError: cannot import name __version__

**Comment by lord63** [comment]
Thanks for the report !  :cake: 
Just released v0.3.2. Please have a try and let me know result.  :cat:

**Comment by wogong** [comment]
@lord63 application successfully started but no output and no log. I'm quite  sure that the config file is OK.

**Comment by lord63** [comment]
@wogong Confirmed.
This problem is easy to fix. Now we have a new big problem #11 . Amazon has changed! So the original way to get the device id failed. I'll try to fix this problem in this weekend and ping you back whether it is solved or not.

**Comment by wogong** [comment]
Got it. Good luck and thanks for your work.
Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.1.27&pv=9.0]
On Wed, Aug 26, 2015 at 20:07, lord63/kindledxpush
<reply@reply.github.com>
wrote:
@wogong [https://github.com/wogong] Confirmed.
This problem is easy to fix. Now we have a new big problem #11 [https://github.com/lord63/kindledxpush/issues/11] . Amazon has changed! So the original way to get the device id failed. I'll try
to fix this problem in this weekend and ping you back whether it is solved or
not.

—
Reply to this email directly or view it on GitHub
[https://github.com/lord63/kindledxpush/issues/10#issuecomment-134969736] .[https://github.com/notifications/beacon/ABeJY_lgTM-qQXbfRtgYlpZzmYGZ93rTks5oraNlgaJpZM4FxydZ.gif]

**Comment by lord63** [comment]
@wogong  Hi, there is a new version 0.3.3 released, should be good to go now. Have a try about this new version and let me know the result.  :smile:

**Comment by wogong** [comment]
@lord63 Cool, it works well now. THANKS!

**Comment by lord63** [comment]
@wogong  Sorry for the inconvenience before, that's my bad. And thanks for your report :sparkles: :cake: :sparkles: , hope you'll enjoy it.
