### ISSUE TITLE
没有metadata1参数也能登陆成功吗？

### ISSUE THREAD

**Issue by fising** [lord63/kindledxpush#8]
没有 metadata1 参数也能登陆成功吗？

**Comment by lord63** [comment]
额，你试试嘛。安装应该挺方便的。在我之前用的时候推送是没有问题的，最近一段时间没有用，你自己试试。
话说你说的 mettadata1 参数具体是要在哪里用到的？

**Comment by fising** [comment]
amazon 登陆需要提交这个参数。

**Comment by lord63** [comment]
哦，我刚刚看了当初抓包时的截图，的确是有这个参数。但是没有这个模拟登录也是没有问题的。
